name: Deploy TypeScript Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # HTTP server
      - name: Install HTTP server deps
        run: npm install
        working-directory: apps/http-server

      - name: Build HTTP server
        run: npm run build
        working-directory: apps/http-server

      # WS server
      - name: Install WS server deps
        run: npm install
        working-directory: apps/ws-server

      - name: Build WS server
        run: npm run build
        working-directory: apps/ws-server

      # Setup SSH key
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/vm_key
          chmod 600 ~/.ssh/vm_key

      # Copy HTTP server to VM using rsync
      - name: Copy HTTP server
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/vm_key -o StrictHostKeyChecking=no" \
            apps/http-server/ \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/cicd/server_deploy/apps/http-server/

      # Copy WS server to VM using rsync
      - name: Copy WS server
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/vm_key -o StrictHostKeyChecking=no" \
            apps/ws-server/ \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/cicd/server_deploy/apps/ws-server/

      # Restart PM2 servers
      - name: Restart PM2 servers
        run: |
          ssh -i ~/.ssh/vm_key -o StrictHostKeyChecking=no \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
            "cd ~/cicd/server_deploy/apps/http-server && pm2 restart http-server || pm2 start npm --name http-server -- start && \
             cd ~/cicd/server_deploy/apps/ws-server && pm2 restart ws-server || pm2 start npm --name ws-server -- start"
